version: '3.8'

services:
  qdrant:
    extends:
      file: docker-compose.yml
      service: qdrant

  init-collections:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - qdrant
    environment:
      - VECTOR_SIZE=1536
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - CANONICAL_COLLECTION=canonical_queries
      - CONVERSATION_COLLECTION=conversations
      - DOCUMENT_COLLECTION=documents
      - MERGED_COLLECTION=merged_knowledge
    command: python /scripts/init_collections.py
